kind: ConfigMap
apiVersion: v1
metadata:
  name: nginx-config
data:
  nginx.conf: |
    events {
    }
    http {
      server {
        listen 80 default_server;
        listen [::]:80 default_server;

        # Set nginx to serve files from the shared volume!
        root /site/public;
        server_name _;
        location / {
          index index.php;
          rewrite   ^(.*)?$ /index.php last;
        }
        location ~ \.php$ {
          include fastcgi_params;
          fastcgi_index index.php;

          fastcgi_param REQUEST_METHOD $request_method;
          fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
          fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
          fastcgi_param PATH_INFO $fastcgi_script_name;

          fastcgi_intercept_errors on;

          fastcgi_pass 127.0.0.1:9000;
        }
      }
    }
