apiVersion: apps/v1
kind: Deployment
metadata:
  name: cubex-translate
  labels:
    app: ctran
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ctran
  template:
    metadata:
      labels:
        app: ctran
    spec:
      volumes:
        - name: nginx-config-volume
          configMap:
            name: nginx-config

      containers:
        - image: gcr.io/cubex-oss/t.cubex.io:7b138e399dacba80061cfb9c24c4840b8312a715
          name: fpm

        - image: nginx:1.19.0-alpine
          name: nginx
          ports:
            - containerPort: 80
              protocol: TCP
          volumeMounts:
            - name: nginx-config-volume
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
